service:
  name: template-service-api

plugins:
  - serverless-dotenv-plugin
  - serverless-stage-manager
  - serverless-pseudo-parameters
  - serverless-webpack
  - serverless-plugin-monorepo
  - serverless-offline
  - serverless-ngrok-tunnel

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-3
  memorySize: 512
  stage: ${opt:stage}
  profile: picnic
  environment:
    SENTRY_ENVIRONMENT: "${self:provider.stage}"
    SENTRY_DNS: "${env:SENTRY_DNS}"
    MONGO_DB_URL: "${env:MONGO_DB_URL}"
    TWILIO_ACCOUNT_SID: "${env:TWILIO_ACCOUNT_SID}"
    TWILIO_API_KEY_SID: "${env:TWILIO_API_KEY_SID}"
    TWILIO_API_KEY_SECRET: "${env:TWILIO_API_KEY_SECRET}"
    SECRET: "${env:SECRET}"
    API_ENDPOINT: "${env:API_ENDPOINT}"

package:
  individually: true

functions:
  join:
    handler: src/handler.join
    events:
      - http:
          path: join
          method: post
  adminRooms:
    handler: src/handler.adminRooms
    events:
      - http:
          path: admin/room
          method: post
  adminParticipants:
    handler: src/handler.adminParticipants
    events:
      - http:
          path: admin/participant
          method: post
  webhookStatus:
    handler: src/handler.webhookStatus
    events:
      - http:
          path: webhook/twilio/status
          method: get
  cron:
    handler: src/handler.cron
    events:
      - schedule: rate(1 minute)

custom:
  ngrokTunnel:
    envPath: "./.env"
    tunnels:
      - port: 4000 # required
        envProp: API_ENDPOINT
        ngrokOptions:
          auth: "user:pwd"
          authtoken: "1jyclDvBLpaLz01TwCzbRYbIHRB_2oWbDViiCC7SGbgEujzdg"
          region: "eu"

  serverless-offline:
    # useChildProcesses: true
    httpPort: 4000

  webpack:
    webpackConfig: "webpack.config.js"
    keepOutputDirectory: true
    includeModules: true
    packager: "yarn"
    excludeFiles: src/**/*.test.js
  stages:
    - dev
    - production
    - staging
