service:
  name: template-service-api

plugins:
  - serverless-dotenv-plugin
  - serverless-stage-manager
  - serverless-pseudo-parameters
  - serverless-webpack
  - serverless-plugin-monorepo
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-3
  memorySize: 512
  stage: ${opt:stage}
  profile: picnic
  environment:
    SENTRY_ENVIRONMENT: "${self:provider.stage}"
    SENTRY_DNS: "${env:SENTRY_DNS}"
    MONGO_DB_URL: "${env:MONGO_DB_URL}"
    TWILIO_ACCOUNT_SID: "${env:TWILIO_ACCOUNT_SID}"
    TWILIO_API_KEY_SID: "${env:TWILIO_API_KEY_SID}"
    TWILIO_API_KEY_SECRET: "${env:TWILIO_API_KEY_SECRET}"

package:
  individually: true

functions:
  join:
    handler: src/handler.join
    events:
      - http:
          path: join
          method: post

custom:
  serverless-offline:
    useChildProcesses: true
    httpPort: 4000

  webpack:
    webpackConfig: "webpack.config.js"
    keepOutputDirectory: true
    includeModules: true
    packager: "yarn"
    excludeFiles: src/**/*.test.js
  stages:
    - dev
    - production
    - staging
