service: room-service-api

frameworkVersion: ^2.11.0

configValidationMode: error

plugins:
  - serverless-dotenv-plugin
  - serverless-stage-manager
  - serverless-domain-manager
  - serverless-pseudo-parameters
  - serverless-webpack
  - serverless-plugin-monorepo
  - serverless-offline
  - serverless-ngrok-tunnel

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-3
  memorySize: 512
  timeout: 30
  logRetentionInDays: 14
  stage: ${opt:stage}
  profile: picnic
  environment:
    SENTRY_ENVIRONMENT: "${self:provider.stage}"
    SENTRY_DNS: "${env:SENTRY_DNS}"
    MONGO_DB_URL: "${env:MONGO_DB_URL}"
    TWILIO_ACCOUNT_SID: "${env:TWILIO_ACCOUNT_SID}"
    TWILIO_API_KEY_SID: "${env:TWILIO_API_KEY_SID}"
    TWILIO_API_KEY_SECRET: "${env:TWILIO_API_KEY_SECRET}"
    TWILIO_AUTH_TOKEN: "${env:TWILIO_AUTH_TOKEN}"
    SECRET: "${env:SECRET}"
    API_ENDPOINT: "${env:API_ENDPOINT}"
    USER_SERVICE_API_SECRET: "${env:USER_SERVICE_API_SECRET}"
    USER_SERVICE_API_ENDPOINT: "${env:USER_SERVICE_API_ENDPOINT}"
    SPACE_SERVICE_API_ENDPOINT: "${env:SPACE_SERVICE_API_ENDPOINT}"
    NGROK: "${env:NGROK}"
    MAX_POOL_SIZE: ${env:MAX_POOL_SIZE, 5}
    MIN_POOL_SIZE: ${env:MIN_POOL_SIZE, 0}
    POOL_SIZE: ${env:POOL_SIZE, 5}
  apiGateway:
    shouldStartNameWithService: true
  tracing:
    apiGateway: true
    lambda: true

package:
  individually: false

functions:
  handler:
    handler: src/handler.handler
    reservedConcurrency: "${env:CONCURRENCY, 100}"
    events:
      - http:
          path: join
          method: post
          cors:
            origin: "*" # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      - http:
          path: admin/room
          method: post
          cors:
            origin: "*" # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      - http:
          path: admin/participant
          method: post
          cors:
            origin: "*" # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      - http:
          path: webhook/twilio/status
          method: post
  cron:
    handler: src/handler.cron
    timeout: 300
    events:
      - schedule: rate(5 minutes)

custom:
  sbs:
    domains:
      production: "room.sidebyside.live"
      staging: "room.dev.sidebyside.live"
      dev: "localhost"

  ngrokTunnel:
    envPath: "./.env"
    tunnels:
      - port: 4002 # required
        envProp: API_ENDPOINT
        ngrokOptions:
          # auth: "user:pwd"
          authtoken: "${env:NGROK}"
          region: "eu"

  serverless-offline:
    useChildProcesses: true
    httpPort: 4002
    lambdaPort: 3005

  webpack:
    webpackConfig: "webpack.config.js"
    keepOutputDirectory: true
    includeModules: true
    packager: "yarn"
    excludeFiles: src/**/*.test.js

  stages:
    - dev
    - production
    - staging

  customDomain:
    domainName: ${self:custom.sbs.domains.${opt:stage, self:provider.stage}}
    stage: ${opt:stage}
    basePath: api
    certificateName: "*.sidebyside.live"
    createRoute53Record: true
    endpointType: "regional"
    apiType: rest
    autoDomain: true
