# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Lint

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-test-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - run: yarn install
  lint_and_build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-test-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - run: yarn install
      - uses: TickX/var-to-dotenv@v1.1.1
        with:
          key: "SENTRY_DNS"
          value: ${{secrets.SENTRY_EXAMPLE_DNS}}
          envPath: "packages/example/.env"
      - run: yarn lint
  stylelint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-test-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - run: yarn install
      - run: yarn lint:style
      - run: yarn prettier:check
  prettier:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-test-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - run: yarn install
      - run: yarn prettier:check
